-- SQL to fix the user's password hash in Supabase
-- This sets the password to M@dmax2026 using our hash algorithm
-- Hash: 6b353c15 (generated by hashPassword('M@dmax2026') with salt='salt')

UPDATE usuarios 
SET 
  senha_hash = '6b353c15',
  updated_at = CURRENT_TIMESTAMP
WHERE email = 'afpereira@saude.sp.gov.br';

-- Verify the change
SELECT email, nome, role, ativo, senha_hash FROM usuarios WHERE email = 'afpereira@saude.sp.gov.br';
