name = "gestor-emendas"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-12"

[env.production]
name = "gestor-emendas"
pages_build_output_dir = "dist"

# Environment variables de produção
[env.production.vars]
SUPABASE_URL = ""
SUPABASE_SERVICE_ROLE_KEY = ""
