-- ============================================================
-- CRIAR TABELA municipio_regional E ATUALIZAR formalizacao
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. CRIAR A TABELA municipio_regional
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS municipio_regional (
  id        SERIAL PRIMARY KEY,
  regional  TEXT NOT NULL,
  municipio TEXT NOT NULL UNIQUE
);

-- ─────────────────────────────────────────────────────────────
-- 2. POPULAR COM OS DADOS DO CSV
-- ─────────────────────────────────────────────────────────────
INSERT INTO municipio_regional (regional, municipio) VALUES
('09 Marília','ADAMANTINA'),
('15 São José do Rio Preto','ADOLFO'),
('14 São João da Boa Vista','AGUAÍ'),
('14 São João da Boa Vista','ÁGUAS DA PRATA'),
('07 Campinas','ÁGUAS DE LINDÓIA'),
('06 Bauru','ÁGUAS DE SANTA BÁRBARA'),
('10 Piracicaba','ÁGUAS DE SÃO PEDRO'),
('06 Bauru','AGUDOS'),
('16 Sorocaba','ALAMBARI'),
('11 Presidente Prudente','ALFREDO MARCONDES'),
('05 Barretos','ALTAIR'),
('13 Ribeirão Preto','ALTINÓPOLIS'),
('02 Araçatuba','ALTO ALEGRE'),
('16 Sorocaba','ALUMÍNIO'),
('15 São José do Rio Preto','ÁLVARES FLORENCE'),
('11 Presidente Prudente','ÁLVARES MACHADO'),
('09 Marília','ÁLVARO DE CARVALHO'),
('09 Marília','ALVINLÂNDIA'),
('07 Campinas','AMERICANA'),
('03 Araraquara','AMÉRICO BRASILIENSE'),
('15 São José do Rio Preto','AMÉRICO DE CAMPOS'),
('07 Campinas','AMPARO'),
('10 Piracicaba','ANALÂNDIA'),
('02 Araçatuba','ANDRADINA'),
('16 Sorocaba','ANGATUBA'),
('06 Bauru','ANHEMBI'),
('11 Presidente Prudente','ANHUMAS'),
('17 Taubaté','APARECIDA'),
('15 São José do Rio Preto','APARECIDA D''OESTE'),
('16 Sorocaba','APIAÍ'),
('16 Sorocaba','ARAÇARIGUAMA'),
('02 Araçatuba','ARAÇATUBA'),
('16 Sorocaba','ARAÇOIABA DA SERRA'),
('08 Franca','ARAMINA'),
('06 Bauru','ARANDU'),
('17 Taubaté','ARAPEÍ'),
('03 Araraquara','ARARAQUARA'),
('10 Piracicaba','ARARAS'),
('09 Marília','ARCO ÍRIS'),
('06 Bauru','AREALVA'),
('17 Taubaté','AREIAS'),
('06 Bauru','AREIÓPOLIS'),
('15 São José do Rio Preto','ARIRANHA'),
('07 Campinas','ARTUR NOGUEIRA'),
('01 Grande São Paulo','ARUJÁ'),
('15 São José do Rio Preto','ASPÁSIA'),
('09 Marília','ASSIS'),
('07 Campinas','ATIBAIA'),
('02 Araçatuba','AURIFLAMA'),
('06 Bauru','AVAÍ'),
('02 Araçatuba','AVANHANDAVA'),
('06 Bauru','AVARÉ'),
('15 São José do Rio Preto','BADY BASSIT'),
('06 Bauru','BALBINOS'),
('15 São José do Rio Preto','BÁLSAMO'),
('17 Taubaté','BANANAL'),
('06 Bauru','BARÃO DE ANTONINA'),
('02 Araçatuba','BARBOSA'),
('06 Bauru','BARIRI'),
('06 Bauru','BARRA BONITA'),
('16 Sorocaba','BARRA DO CHAPÉU'),
('12 Registro','BARRA DO TURVO'),
('05 Barretos','BARRETOS'),
('13 Ribeirão Preto','BARRINHA'),
('01 Grande São Paulo','BARUERI'),
('09 Marília','BASTOS'),
('13 Ribeirão Preto','BATATAIS'),
('06 Bauru','BAURU'),
('05 Barretos','BEBEDOURO'),
('02 Araçatuba','BENTO DE ABREU'),
('09 Marília','BERNARDINO DE CAMPOS'),
('04 Baixada Santista','BERTIOGA'),
('02 Araçatuba','BILAC'),
('02 Araçatuba','BIRIGUI'),
('01 Grande São Paulo','BIRITIBA-MIRIM'),
('03 Araraquara','BOA ESPERANÇA DO SUL'),
('06 Bauru','BOCAINA'),
('06 Bauru','BOFETE'),
('16 Sorocaba','BOITUVA'),
('07 Campinas','BOM JESUS DOS PERDÕES'),
('16 Sorocaba','BOM SUCESSO DE ITARARÉ'),
('09 Marília','BORÁ'),
('06 Bauru','BORACÉIA'),
('03 Araraquara','BORBOREMA'),
('06 Bauru','BOREBI'),
('06 Bauru','BOTUCATU'),
('07 Campinas','BRAGANÇA PAULISTA'),
('02 Araçatuba','BRAÚNA'),
('02 Araçatuba','BREJO ALEGRE'),
('13 Ribeirão Preto','BRODOWSKI'),
('06 Bauru','BROTAS'),
('16 Sorocaba','BURI'),
('02 Araçatuba','BURITAMA'),
('08 Franca','BURITIZAL'),
('06 Bauru','CABRÁLIA PAULISTA'),
('07 Campinas','CABREÚVA'),
('17 Taubaté','CAÇAPAVA'),
('17 Taubaté','CACHOEIRA PAULISTA'),
('14 São João da Boa Vista','CACONDE'),
('06 Bauru','CAFELÂNDIA'),
('11 Presidente Prudente','CAIABU'),
('01 Grande São Paulo','CAIEIRAS'),
('11 Presidente Prudente','CAIUÁ'),
('01 Grande São Paulo','CAJAMAR'),
('12 Registro','CAJATI'),
('05 Barretos','CAJOBI'),
('13 Ribeirão Preto','CAJURU'),
('16 Sorocaba','CAMPINA DO MONTE ALEGRE'),
('07 Campinas','CAMPINAS'),
('07 Campinas','CAMPO LIMPO PAULISTA'),
('17 Taubaté','CAMPOS DO JORDÃO'),
('09 Marília','CAMPOS NOVOS PAULISTA'),
('12 Registro','CANANÉIA'),
('17 Taubaté','CANAS'),
('09 Marília','CÂNDIDO MOTA'),
('03 Araraquara','CÂNDIDO RODRIGUES'),
('09 Marília','CANITAR'),
('16 Sorocaba','CAPÃO BONITO'),
('16 Sorocaba','CAPELA DO ALTO'),
('10 Piracicaba','CAPIVARI'),
('17 Taubaté','CARAGUATATUBA'),
('01 Grande São Paulo','CARAPICUÍBA'),
('15 São José do Rio Preto','CARDOSO'),
('14 São João da Boa Vista','CASA BRANCA'),
('13 Ribeirão Preto','CÁSSIA DOS COQUEIROS'),
('02 Araçatuba','CASTILHO'),
('15 São José do Rio Preto','CATANDUVA'),
('15 São José do Rio Preto','CATIGUÁ'),
('15 São José do Rio Preto','CEDRAL'),
('06 Bauru','CERQUEIRA CÉSAR'),
('16 Sorocaba','CERQUILHO'),
('16 Sorocaba','CESÁRIO LANGE'),
('10 Piracicaba','CHARQUEADA'),
('09 Marília','CHAVANTES'),
('02 Araçatuba','CLEMENTINA'),
('05 Barretos','COLINA'),
('05 Barretos','COLÔMBIA'),
('10 Piracicaba','CONCHAL'),
('06 Bauru','CONCHAS'),
('10 Piracicaba','CORDEIRÓPOLIS'),
('02 Araçatuba','COROADOS'),
('06 Bauru','CORONEL MACEDO'),
('10 Piracicaba','CORUMBATAÍ'),
('07 Campinas','COSMÓPOLIS'),
('15 São José do Rio Preto','COSMORAMA'),
('01 Grande São Paulo','COTIA'),
('13 Ribeirão Preto','CRAVINHOS'),
('08 Franca','CRISTAIS PAULISTA'),
('09 Marília','CRUZÁLIA'),
('17 Taubaté','CRUZEIRO'),
('04 Baixada Santista','CUBATÃO'),
('17 Taubaté','CUNHA'),
('03 Araraquara','DESCALVADO'),
('01 Grande São Paulo','DIADEMA'),
('15 São José do Rio Preto','DIRCE REIS'),
('14 São João da Boa Vista','DIVINOLÂNDIA'),
('03 Araraquara','DOBRADA'),
('06 Bauru','DOIS CÓRREGOS'),
('15 São José do Rio Preto','DOLCINÓPOLIS'),
('03 Araraquara','DOURADO'),
('11 Presidente Prudente','DRACENA'),
('06 Bauru','DUARTINA'),
('13 Ribeirão Preto','DUMONT'),
('09 Marília','ECHAPORÃ'),
('12 Registro','ELDORADO'),
('10 Piracicaba','ELIAS FAUSTO'),
('15 São José do Rio Preto','ELISIÁRIO'),
('15 São José do Rio Preto','EMBAÚBA'),
('01 Grande São Paulo','EMBU'),
('01 Grande São Paulo','EMBU-GUAÇU'),
('11 Presidente Prudente','EMILIANÓPOLIS'),
('10 Piracicaba','ENGENHEIRO COELHO'),
('14 São João da Boa Vista','ESPÍRITO SANTO DO PINHAL'),
('09 Marília','ESPÍRITO SANTO DO TURVO'),
('14 São João da Boa Vista','ESTIVA GERBI'),
('11 Presidente Prudente','ESTRELA DO NORTE'),
('15 São José do Rio Preto','ESTRELA D''OESTE'),
('11 Presidente Prudente','EUCLIDES DA CUNHA PAULISTA'),
('06 Bauru','FARTURA'),
('15 São José do Rio Preto','FERNANDO PRESTES'),
('15 São José do Rio Preto','FERNANDÓPOLIS'),
('09 Marília','FERNÃO'),
('01 Grande São Paulo','FERRAZ DE VASCONCELOS'),
('11 Presidente Prudente','FLORA RICA'),
('15 São José do Rio Preto','FLOREAL'),
('09 Marília','FLÓRIDA PAULISTA'),
('09 Marília','FLORÍNIA'),
('08 Franca','FRANCA'),
('01 Grande São Paulo','FRANCISCO MORATO'),
('01 Grande São Paulo','FRANCO DA ROCHA'),
('02 Araçatuba','GABRIEL MONTEIRO'),
('09 Marília','GÁLIA'),
('09 Marília','GARÇA'),
('15 São José do Rio Preto','GASTÃO VIDIGAL'),
('03 Araraquara','GAVIÃO PEIXOTO'),
('15 São José do Rio Preto','GENERAL SALGADO'),
('06 Bauru','GETULINA'),
('02 Araçatuba','GLICÉRIO'),
('06 Bauru','GUAIÇARA'),
('09 Marília','GUAIMBÊ'),
('05 Barretos','GUAÍRA'),
('15 São José do Rio Preto','GUAPIAÇU'),
('16 Sorocaba','GUAPIARA'),
('08 Franca','GUARÁ'),
('02 Araçatuba','GUARAÇAÍ'),
('05 Barretos','GUARACI'),
('15 São José do Rio Preto','GUARANI D''OESTE'),
('09 Marília','GUARANTÃ'),
('02 Araçatuba','GUARARAPES'),
('01 Grande São Paulo','GUARAREMA'),
('17 Taubaté','GUARATINGUETÁ'),
('16 Sorocaba','GUAREÍ'),
('13 Ribeirão Preto','GUARIBA'),
('04 Baixada Santista','GUARUJÁ'),
('01 Grande São Paulo','GUARULHOS'),
('13 Ribeirão Preto','GUATAPARÁ'),
('02 Araçatuba','GUZOLÂNDIA'),
('09 Marília','HERCULÂNDIA'),
('07 Campinas','HOLAMBRA'),
('07 Campinas','HORTOLÂNDIA'),
('06 Bauru','IACANGA'),
('09 Marília','IACRI'),
('06 Bauru','IARAS'),
('03 Araraquara','IBATÉ'),
('15 São José do Rio Preto','IBIRÁ'),
('09 Marília','IBIRAREMA'),
('03 Araraquara','IBITINGA'),
('16 Sorocaba','IBIÚNA'),
('15 São José do Rio Preto','ICÉM'),
('11 Presidente Prudente','IEPÊ'),
('06 Bauru','IGARAÇU DO TIETÊ'),
('08 Franca','IGARAPAVA'),
('17 Taubaté','IGARATÁ'),
('12 Registro','IGUAPE'),
('17 Taubaté','ILHA BELA'),
('12 Registro','ILHA COMPRIDA'),
('02 Araçatuba','ILHA SOLTEIRA'),
('07 Campinas','INDAIATUBA'),
('11 Presidente Prudente','INDIANA'),
('15 São José do Rio Preto','INDIAPORÃ'),
('09 Marília','INÚBIA PAULISTA'),
('09 Marília','IPAUSSU'),
('16 Sorocaba','IPERÓ'),
('10 Piracicaba','IPEÚNA'),
('15 São José do Rio Preto','IPIGUÁ'),
('12 Registro','IPORANGA'),
('08 Franca','IPUÃ'),
('10 Piracicaba','IRACEMÁPOLIS'),
('15 São José do Rio Preto','IRAPUÃ'),
('11 Presidente Prudente','IRAPURU'),
('16 Sorocaba','ITABERÁ'),
('06 Bauru','ITAÍ'),
('15 São José do Rio Preto','ITAJOBI'),
('06 Bauru','ITAJU'),
('04 Baixada Santista','ITANHAÉM'),
('16 Sorocaba','ITAÓCA'),
('01 Grande São Paulo','ITAPECERICA DA SERRA'),
('16 Sorocaba','ITAPETININGA'),
('16 Sorocaba','ITAPEVA'),
('01 Grande São Paulo','ITAPEVI'),
('14 São João da Boa Vista','ITAPIRA'),
('16 Sorocaba','ITAPIRAPUÃ PAULISTA'),
('03 Araraquara','ITÁPOLIS'),
('06 Bauru','ITAPORANGA'),
('06 Bauru','ITAPUÍ'),
('02 Araçatuba','ITAPURA'),
('01 Grande São Paulo','ITAQUAQUECETUBA'),
('16 Sorocaba','ITARARÉ'),
('12 Registro','ITARIRI'),
('07 Campinas','ITATIBA'),
('06 Bauru','ITATINGA'),
('10 Piracicaba','ITIRAPINA'),
('08 Franca','ITIRAPUÃ'),
('14 São João da Boa Vista','ITOBI'),
('16 Sorocaba','ITU'),
('07 Campinas','ITUPEVA'),
('08 Franca','ITUVERAVA'),
('05 Barretos','JABORANDI'),
('13 Ribeirão Preto','JABOTICABAL'),
('17 Taubaté','JACAREÍ'),
('15 São José do Rio Preto','JACI'),
('12 Registro','JACUPIRANGA'),
('07 Campinas','JAGUARIÚNA'),
('15 São José do Rio Preto','JALES'),
('17 Taubaté','JAMBEIRO'),
('01 Grande São Paulo','JANDIRA'),
('13 Ribeirão Preto','JARDINÓPOLIS'),
('07 Campinas','JARINU'),
('06 Bauru','JAÚ'),
('08 Franca','JERIQUARA'),
('07 Campinas','JOANÓPOLIS'),
('11 Presidente Prudente','JOÃO RAMALHO'),
('15 São José do Rio Preto','JOSÉ BONIFÁCIO'),
('09 Marília','JÚLIO MESQUITA'),
('16 Sorocaba','JUMIRIM'),
('07 Campinas','JUNDIAÍ'),
('11 Presidente Prudente','JUNQUEIRÓPOLIS'),
('12 Registro','JUQUIÁ'),
('01 Grande São Paulo','JUQUITIBA'),
('17 Taubaté','LAGOINHA'),
('06 Bauru','LARANJAL PAULISTA'),
('02 Araçatuba','LAVÍNIA'),
('17 Taubaté','LAVRINHAS'),
('10 Piracicaba','LEME'),
('06 Bauru','LENÇÓIS PAULISTA'),
('10 Piracicaba','LIMEIRA'),
('07 Campinas','LINDÓIA'),
('06 Bauru','LINS'),
('17 Taubaté','LORENA'),
('02 Araçatuba','LOURDES'),
('07 Campinas','LOUVEIRA'),
('09 Marília','LUCÉLIA'),
('06 Bauru','LUCIANÓPOLIS'),
('13 Ribeirão Preto','LUÍS ANTÔNIO'),
('02 Araçatuba','LUIZIÂNIA'),
('09 Marília','LUPÉRCIO'),
('09 Marília','LUTÉCIA'),
('06 Bauru','MACATUBA'),
('15 São José do Rio Preto','MACAUBAL'),
('15 São José do Rio Preto','MACEDÔNIA'),
('15 São José do Rio Preto','MAGDA'),
('16 Sorocaba','MAIRINQUE'),
('01 Grande São Paulo','MAIRIPORÃ'),
('06 Bauru','MANDURI'),
('11 Presidente Prudente','MARABÁ PAULISTA'),
('09 Marília','MARACAÍ'),
('15 São José do Rio Preto','MARAPOAMA'),
('09 Marília','MARIÁPOLIS'),
('09 Marília','MARÍLIA'),
('15 São José do Rio Preto','MARINÓPOLIS'),
('11 Presidente Prudente','MARTINÓPOLIS'),
('03 Araraquara','MATÃO'),
('01 Grande São Paulo','MAUÁ'),
('15 São José do Rio Preto','MENDONÇA'),
('15 São José do Rio Preto','MERIDIANO'),
('15 São José do Rio Preto','MESÓPOLIS'),
('08 Franca','MIGUELÓPOLIS'),
('06 Bauru','MINEIROS DO TIETÊ'),
('15 São José do Rio Preto','MIRA ESTRELA'),
('12 Registro','MIRACATU'),
('02 Araçatuba','MIRANDÓPOLIS'),
('11 Presidente Prudente','MIRANTE DO PARANAPANEMA'),
('15 São José do Rio Preto','MIRASSOL'),
('15 São José do Rio Preto','MIRASSOLÂNDIA'),
('14 São João da Boa Vista','MOCOCA'),
('01 Grande São Paulo','MOGI DAS CRUZES'),
('14 São João da Boa Vista','MOGI GUAÇU'),
('14 São João da Boa Vista','MOGI MIRIM'),
('10 Piracicaba','MOMBUCA'),
('15 São José do Rio Preto','MONÇÕES'),
('04 Baixada Santista','MONGAGUÁ'),
('07 Campinas','MONTE ALEGRE DO SUL'),
('13 Ribeirão Preto','MONTE ALTO'),
('15 São José do Rio Preto','MONTE APRAZÍVEL'),
('05 Barretos','MONTE AZUL PAULISTA'),
('11 Presidente Prudente','MONTE CASTELO'),
('07 Campinas','MONTE MOR'),
('17 Taubaté','MONTEIRO LOBATO'),
('08 Franca','MORRO AGUDO'),
('07 Campinas','MORUNGABA'),
('03 Araraquara','MOTUCA'),
('02 Araçatuba','MURUTINGA DO SUL'),
('11 Presidente Prudente','NANTES'),
('11 Presidente Prudente','NARANDIBA'),
('17 Taubaté','NATIVIDADE DA SERRA'),
('07 Campinas','NAZARÉ PAULISTA'),
('15 São José do Rio Preto','NEVES PAULISTA'),
('15 São José do Rio Preto','NHANDEARA'),
('15 São José do Rio Preto','NIPOÃ'),
('15 São José do Rio Preto','NOVA ALIANÇA'),
('16 Sorocaba','NOVA CAMPINA'),
('15 São José do Rio Preto','NOVA CANAÃ PAULISTA'),
('02 Araçatuba','NOVA CASTILHO'),
('03 Araraquara','NOVA EUROPA'),
('15 São José do Rio Preto','NOVA GRANADA'),
('11 Presidente Prudente','NOVA GUATAPORANGA'),
('02 Araçatuba','NOVA INDEPENDÊNCIA'),
('02 Araçatuba','NOVA LUZITÂNIA'),
('07 Campinas','NOVA ODESSA'),
('15 São José do Rio Preto','NOVAIS'),
('15 São José do Rio Preto','NOVO HORIZONTE'),
('08 Franca','NUPORANGA'),
('09 Marília','OCAUÇU'),
('09 Marília','ÓLEO'),
('05 Barretos','OLÍMPIA'),
('15 São José do Rio Preto','ONDA VERDE'),
('09 Marília','ORIENTE'),
('15 São José do Rio Preto','ORINDIÚVA'),
('08 Franca','ORLÂNDIA'),
('01 Grande São Paulo','OSASCO'),
('09 Marília','OSCAR BRESSANE'),
('09 Marília','OSVALDO CRUZ'),
('09 Marília','OURINHOS'),
('11 Presidente Prudente','OURO VERDE'),
('15 São José do Rio Preto','OUROESTE'),
('09 Marília','PACAEMBU'),
('15 São José do Rio Preto','PALESTINA'),
('15 São José do Rio Preto','PALMARES PAULISTA'),
('15 São José do Rio Preto','PALMEIRA D''OESTE'),
('09 Marília','PALMITAL'),
('11 Presidente Prudente','PANORAMA'),
('09 Marília','PARAGUAÇU PAULISTA'),
('17 Taubaté','PARAIBUNA'),
('15 São José do Rio Preto','PARAÍSO'),
('06 Bauru','PARANAPANEMA'),
('15 São José do Rio Preto','PARANAPUÃ'),
('09 Marília','PARAPUÃ'),
('06 Bauru','PARDINHO'),
('12 Registro','PARIQUERA-AÇU'),
('15 São José do Rio Preto','PARISI'),
('08 Franca','PATROCÍNIO PAULISTA'),
('11 Presidente Prudente','PAULICÉIA'),
('07 Campinas','PAULÍNIA'),
('06 Bauru','PAULISTÂNIA'),
('15 São José do Rio Preto','PAULO DE FARIA'),
('06 Bauru','PEDERNEIRAS'),
('07 Campinas','PEDRA BELA'),
('15 São José do Rio Preto','PEDRANÓPOLIS'),
('08 Franca','PEDREGULHO'),
('07 Campinas','PEDREIRA'),
('09 Marília','PEDRINHAS PAULISTA'),
('12 Registro','PEDRO DE TOLEDO'),
('02 Araçatuba','PENÁPOLIS'),
('02 Araçatuba','PEREIRA BARRETO'),
('06 Bauru','PEREIRAS'),
('04 Baixada Santista','PERUÍBE'),
('02 Araçatuba','PIACATU'),
('16 Sorocaba','PIEDADE'),
('16 Sorocaba','PILAR DO SUL'),
('17 Taubaté','PINDAMONHANGABA'),
('15 São José do Rio Preto','PINDORAMA'),
('07 Campinas','PINHALZINHO'),
('11 Presidente Prudente','PIQUEROBI'),
('17 Taubaté','PIQUETE'),
('07 Campinas','PIRACAIA'),
('10 Piracicaba','PIRACICABA'),
('06 Bauru','PIRAJU'),
('06 Bauru','PIRAJUÍ'),
('15 São José do Rio Preto','PIRANGI'),
('01 Grande São Paulo','PIRAPORA DO BOM JESUS'),
('11 Presidente Prudente','PIRAPOZINHO'),
('10 Piracicaba','PIRASSUNUNGA'),
('06 Bauru','PIRATININGA'),
('13 Ribeirão Preto','PITANGUEIRAS'),
('15 São José do Rio Preto','PLANALTO'),
('09 Marília','PLATINA'),
('01 Grande São Paulo','POÁ'),
('15 São José do Rio Preto','POLONI'),
('09 Marília','POMPÉIA'),
('06 Bauru','PONGAÍ'),
('13 Ribeirão Preto','PONTAL'),
('15 São José do Rio Preto','PONTALINDA'),
('15 São José do Rio Preto','PONTES GESTAL'),
('15 São José do Rio Preto','POPULINA'),
('06 Bauru','PORANGABA'),
('16 Sorocaba','PORTO FELIZ'),
('03 Araraquara','PORTO FERREIRA'),
('17 Taubaté','POTIM'),
('15 São José do Rio Preto','POTIRENDABA'),
('09 Marília','PRACINHA'),
('13 Ribeirão Preto','PRADÓPOLIS'),
('04 Baixada Santista','PRAIA GRANDE'),
('06 Bauru','PRATÂNIA'),
('06 Bauru','PRESIDENTE ALVES'),
('11 Presidente Prudente','PRESIDENTE BERNARDES'),
('11 Presidente Prudente','PRESIDENTE EPITÁCIO'),
('11 Presidente Prudente','PRESIDENTE PRUDENTE'),
('11 Presidente Prudente','PRESIDENTE VENCESLAU'),
('06 Bauru','PROMISSÃO'),
('16 Sorocaba','QUADRA'),
('11 Presidente Prudente','QUATÁ'),
('09 Marília','QUEIROZ'),
('17 Taubaté','QUELUZ'),
('09 Marília','QUINTANA'),
('10 Piracicaba','RAFARD'),
('11 Presidente Prudente','RANCHARIA'),
('17 Taubaté','REDENÇÃO DA SERRA'),
('11 Presidente Prudente','REGENTE FEIJÓ'),
('06 Bauru','REGINÓPOLIS'),
('12 Registro','REGISTRO'),
('08 Franca','RESTINGA'),
('16 Sorocaba','RIBEIRA'),
('03 Araraquara','RIBEIRÃO BONITO'),
('16 Sorocaba','RIBEIRÃO BRANCO'),
('08 Franca','RIBEIRÃO CORRENTE'),
('09 Marília','RIBEIRÃO DO SUL'),
('11 Presidente Prudente','RIBEIRÃO DOS ÍNDIOS'),
('16 Sorocaba','RIBEIRÃO GRANDE'),
('01 Grande São Paulo','RIBEIRÃO PIRES'),
('13 Ribeirão Preto','RIBEIRÃO PRETO'),
('08 Franca','RIFAINA'),
('03 Araraquara','RINCÃO'),
('09 Marília','RINÓPOLIS'),
('10 Piracicaba','RIO CLARO'),
('10 Piracicaba','RIO DAS PEDRAS'),
('01 Grande São Paulo','RIO GRANDE DA SERRA'),
('15 São José do Rio Preto','RIOLÂNDIA'),
('16 Sorocaba','RIVERSUL'),
('11 Presidente Prudente','ROSANA'),
('17 Taubaté','ROSEIRA'),
('02 Araçatuba','RUBIÁCEA'),
('15 São José do Rio Preto','RUBINÉIA'),
('06 Bauru','SABINO'),
('09 Marília','SAGRES'),
('15 São José do Rio Preto','SALES'),
('08 Franca','SALES OLIVEIRA'),
('01 Grande São Paulo','SALESÓPOLIS'),
('09 Marília','SALMOURÃO'),
('10 Piracicaba','SALTINHO'),
('16 Sorocaba','SALTO'),
('16 Sorocaba','SALTO DE PIRAPORA'),
('09 Marília','SALTO GRANDE'),
('11 Presidente Prudente','SANDOVALINA'),
('15 São José do Rio Preto','SANTA ADÉLIA'),
('15 São José do Rio Preto','SANTA ALBERTINA'),
('07 Campinas','SANTA BÁRBARA D''OESTE'),
('17 Taubaté','SANTA BRANCA'),
('15 São José do Rio Preto','SANTA CLARA D''OESTE'),
('10 Piracicaba','SANTA CRUZ DA CONCEIÇÃO'),
('13 Ribeirão Preto','SANTA CRUZ DA ESPERANÇA'),
('14 São João da Boa Vista','SANTA CRUZ DAS PALMEIRAS'),
('09 Marília','SANTA CRUZ DO RIO PARDO'),
('03 Araraquara','SANTA ERNESTINA'),
('15 São José do Rio Preto','SANTA FÉ DO SUL'),
('10 Piracicaba','SANTA GERTRUDES'),
('01 Grande São Paulo','SANTA ISABEL'),
('03 Araraquara','SANTA LÚCIA'),
('10 Piracicaba','SANTA MARIA DA SERRA'),
('11 Presidente Prudente','SANTA MERCEDES'),
('13 Ribeirão Preto','SANTA RITA DO PASSA QUATRO'),
('15 São José do Rio Preto','SANTA RITA DOESTE'),
('13 Ribeirão Preto','SANTA ROSA DE VITERBO'),
('15 São José do Rio Preto','SANTA SALETE'),
('15 São José do Rio Preto','SANTANA DA PONTE PENSA'),
('01 Grande São Paulo','SANTANA DE PARNAÍBA'),
('11 Presidente Prudente','SANTO ANASTÁCIO'),
('01 Grande São Paulo','SANTO ANDRÉ'),
('13 Ribeirão Preto','SANTO ANTÔNIO DA ALEGRIA'),
('07 Campinas','SANTO ANTÔNIO DA POSSE'),
('02 Araçatuba','SANTO ANTÔNIO DO ARACANGUÁ'),
('14 São João da Boa Vista','SANTO ANTÔNIO DO JARDIM'),
('17 Taubaté','SANTO ANTÔNIO DO PINHAL'),
('11 Presidente Prudente','SANTO EXPEDITO'),
('02 Araçatuba','SANTÓPOLIS DO AGUAPEÍ'),
('04 Baixada Santista','SANTOS'),
('17 Taubaté','SÃO BENTO DO SAPUCAÍ'),
('01 Grande São Paulo','SÃO BERNARDO DO CAMPO'),
('01 Grande São Paulo','SÃO CAETANO DO SUL'),
('03 Araraquara','SÃO CARLOS'),
('15 São José do Rio Preto','SÃO FRANCISCO'),
('14 São João da Boa Vista','SÃO JOÃO DA BOA VISTA'),
('15 São José do Rio Preto','SÃO JOÃO DAS DUAS PONTES'),
('15 São José do Rio Preto','SÃO JOÃO DE IRACEMA'),
('11 Presidente Prudente','SÃO JOÃO DO PAU D''ALHO'),
('08 Franca','SÃO JOAQUIM DA BARRA'),
('08 Franca','SÃO JOSÉ DA BELA VISTA'),
('17 Taubaté','SÃO JOSÉ DO BARREIRO'),
('14 São João da Boa Vista','SÃO JOSÉ DO RIO PARDO'),
('15 São José do Rio Preto','SÃO JOSÉ DO RIO PRETO'),
('17 Taubaté','SÃO JOSÉ DOS CAMPOS'),
('01 Grande São Paulo','SÃO LOURENÇO DA SERRA'),
('17 Taubaté','SÃO LUIZ DO PARAITINGA'),
('06 Bauru','SÃO MANUEL'),
('16 Sorocaba','SÃO MIGUEL ARCANJO'),
('01 Grande São Paulo','SÃO PAULO'),
('10 Piracicaba','SÃO PEDRO'),
('09 Marília','SÃO PEDRO DO TURVO'),
('16 Sorocaba','SÃO ROQUE'),
('17 Taubaté','SÃO SEBASTIÃO'),
('14 São João da Boa Vista','SÃO SEBASTIÃO DA GRAMA'),
('13 Ribeirão Preto','SÃO SIMÃO'),
('04 Baixada Santista','SÃO VICENTE'),
('16 Sorocaba','SARAPUÍ'),
('06 Bauru','SARUTAIÁ'),
('15 São José do Rio Preto','SEBASTIANÓPOLIS DO SUL'),
('13 Ribeirão Preto','SERRA AZUL'),
('07 Campinas','SERRA NEGRA'),
('13 Ribeirão Preto','SERRANA'),
('13 Ribeirão Preto','SERTÃOZINHO'),
('12 Registro','SETE BARRAS'),
('05 Barretos','SEVERÍNIA'),
('17 Taubaté','SILVEIRAS'),
('07 Campinas','SOCORRO'),
('16 Sorocaba','SOROCABA'),
('02 Araçatuba','SUD MENNUCCI'),
('07 Campinas','SUMARÉ'),
('02 Araçatuba','SUZANÁPOLIS'),
('01 Grande São Paulo','SUZANO'),
('15 São José do Rio Preto','TABAPUÃ'),
('03 Araraquara','TABATINGA'),
('01 Grande São Paulo','TABOÃO DA SERRA'),
('11 Presidente Prudente','TACIBA'),
('06 Bauru','TAGUAÍ'),
('05 Barretos','TAIAÇU'),
('05 Barretos','TAIÚVA'),
('14 São João da Boa Vista','TAMBAÚ'),
('15 São José do Rio Preto','TANABI'),
('16 Sorocaba','TAPIRAÍ'),
('14 São João da Boa Vista','TAPIRATIBA'),
('05 Barretos','TAQUARAL'),
('03 Araraquara','TAQUARITINGA'),
('06 Bauru','TAQUARITUBA'),
('16 Sorocaba','TAQUARIVAÍ'),
('11 Presidente Prudente','TARABAI'),
('09 Marília','TARUMÃ'),
('16 Sorocaba','TATUÍ'),
('17 Taubaté','TAUBATÉ'),
('06 Bauru','TEJUPÁ'),
('11 Presidente Prudente','TEODORO SAMPAIO'),
('05 Barretos','TERRA ROXA'),
('16 Sorocaba','TIETÊ'),
('09 Marília','TIMBURI'),
('06 Bauru','TORRE DE PEDRA'),
('06 Bauru','TORRINHA'),
('03 Araraquara','TRABIJU'),
('17 Taubaté','TREMEMBÉ'),
('15 São José do Rio Preto','TRÊS FRONTEIRAS'),
('07 Campinas','TUIUTI'),
('09 Marília','TUPÃ'),
('11 Presidente Prudente','TUPI PAULISTA'),
('02 Araçatuba','TURIÚBA'),
('15 São José do Rio Preto','TURMALINA'),
('15 São José do Rio Preto','UBARANA'),
('17 Taubaté','UBATUBA'),
('09 Marília','UBIRAJARA'),
('15 São José do Rio Preto','UCHOA'),
('15 São José do Rio Preto','UNIÃO PAULISTA'),
('15 São José do Rio Preto','URÂNIA'),
('06 Bauru','URU'),
('15 São José do Rio Preto','URUPÊS'),
('15 São José do Rio Preto','VALENTIM GENTIL'),
('07 Campinas','VALINHOS'),
('02 Araçatuba','VALPARAÍSO'),
('07 Campinas','VARGEM'),
('14 São João da Boa Vista','VARGEM GRANDE DO SUL'),
('01 Grande São Paulo','VARGEM GRANDE PAULISTA'),
('07 Campinas','VÁRZEA PAULISTA'),
('09 Marília','VERA CRUZ'),
('07 Campinas','VINHEDO'),
('05 Barretos','VIRADOURO'),
('05 Barretos','VISTA ALEGRE DO ALTO'),
('15 São José do Rio Preto','VITÓRIA BRASIL'),
('16 Sorocaba','VOTORANTIM'),
('15 São José do Rio Preto','VOTUPORANGA'),
('15 São José do Rio Preto','ZACARIAS')
ON CONFLICT (municipio) DO UPDATE SET regional = EXCLUDED.regional;

-- ─────────────────────────────────────────────────────────────
-- 3. VERIFICAR: quantos municípios foram inseridos
-- ─────────────────────────────────────────────────────────────
SELECT COUNT(*) AS total_municipios FROM municipio_regional;

-- ─────────────────────────────────────────────────────────────
-- 4. VISUALIZAR: impacto da atualização (preview antes de executar)
--    Todos os registros com município encontrado serão atualizados
-- ─────────────────────────────────────────────────────────────
SELECT
  COUNT(*) FILTER (
    WHERE UPPER(TRIM(f.municipio)) = mr.municipio
      AND (f.regional IS NULL OR TRIM(f.regional) = '')
  ) AS serao_preenchidas_vazias,
  COUNT(*) FILTER (
    WHERE UPPER(TRIM(f.municipio)) = mr.municipio
      AND f.regional IS NOT NULL AND TRIM(f.regional) <> ''
      AND f.regional <> mr.regional
  ) AS serao_corrigidas_valor_diferente,
  COUNT(*) FILTER (
    WHERE NOT EXISTS (
      SELECT 1 FROM municipio_regional mr2
      WHERE mr2.municipio = UPPER(TRIM(f.municipio))
    )
  ) AS municipio_nao_encontrado,
  COUNT(*) AS total
FROM formalizacao f
LEFT JOIN municipio_regional mr ON mr.municipio = UPPER(TRIM(f.municipio));

-- ─────────────────────────────────────────────────────────────
-- 5. EXECUTAR: preencher/corrigir regional em TODOS os registros de formalizacao
--    Atualiza regional independente do valor atual (padroniza todos)
-- ─────────────────────────────────────────────────────────────
BEGIN;

UPDATE formalizacao f
SET
  regional   = mr.regional,
  updated_at = NOW()
FROM municipio_regional mr
WHERE mr.municipio = UPPER(TRIM(f.municipio));

SELECT COUNT(*) AS linhas_atualizadas
FROM formalizacao
WHERE updated_at >= NOW() - INTERVAL '10 seconds';

COMMIT;


-- ─────────────────────────────────────────────────────────────
-- 6b. CRIAR TRIGGER: preencher regional automaticamente
--     em INSERT ou UPDATE de municipio na tabela formalizacao
-- ─────────────────────────────────────────────────────────────

-- Função chamada pelo trigger
CREATE OR REPLACE FUNCTION fn_preencher_regional_por_municipio()
RETURNS TRIGGER AS $$
BEGIN
  -- Só executa se municipio estiver preenchido
  IF NEW.municipio IS NOT NULL AND TRIM(NEW.municipio) <> '' THEN
    SELECT regional
    INTO NEW.regional
    FROM municipio_regional
    WHERE municipio = UPPER(TRIM(NEW.municipio))
    LIMIT 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Remove o trigger se já existir (para poder recriar)
DROP TRIGGER IF EXISTS trg_preencher_regional ON formalizacao;

-- Cria o trigger BEFORE INSERT OR UPDATE
CREATE TRIGGER trg_preencher_regional
BEFORE INSERT OR UPDATE OF municipio ON formalizacao
FOR EACH ROW
EXECUTE FUNCTION fn_preencher_regional_por_municipio();

-- Confirmar que o trigger foi criado
SELECT trigger_name, event_manipulation, action_timing
FROM information_schema.triggers
WHERE event_object_table = 'formalizacao'
  AND trigger_name = 'trg_preencher_regional';

-- ─────────────────────────────────────────────────────────────
-- 6. VERIFICAR: municípios em formalizacao sem regional
--    (não encontrados na tabela de referência)
-- ─────────────────────────────────────────────────────────────
SELECT UPPER(TRIM(municipio)) AS municipio_sem_regional, COUNT(*) AS qtd
FROM formalizacao
WHERE (regional IS NULL OR TRIM(regional) = '')
  AND municipio IS NOT NULL AND TRIM(municipio) <> ''
GROUP BY 1
ORDER BY 2 DESC
LIMIT 30;
